//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FtpConnection
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public Nullable<int> Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public int SchedCount { get; set; }
        public string SchedMeasure { get; set; }
        public string Protocol { get; set; }
    }
}
